# Homebrew
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# General purpose
brew "rcm"
brew "git"
brew "ack"
brew "trash"
brew "tree"
brew "neovim"
brew "asdf"

# Ruby
brew "ruby-build"
brew "rbenv"

# Tmux
brew "reattach-to-user-namespace"
brew "tmux"

# Vim
# brew "vim"
# brew "the_silver_searcher"

# Bash
# brew "bash-completion"
# brew "coreutils"

# Cask
cask "mysqlworkbench"
cask "google-chrome"
cask "slack"
cask "sublime-text"
cask "transmission"
cask "vlc"
cask "iterm2"
cask "docker"
cask "postico"
cask "sourcetree"
cask "spotify"
cask "whatsapp"

# Skipped (after scanning the `brew list`):
#  - kubernetes-cli
#  - ripgrep
#  - tree-sitter
#  - lua
#  - luajit
