# Homebrew
tap "homebrew/bundle"
tap "homebrew/services"

# General
brew "rcm"
brew "git"
brew "ack"
brew "tree"
brew "asdf"
brew "macos-trash"

# Ruby
brew "ruby-build"
brew "rbenv"

# Tmux
brew "tmux"

# Neovim
brew "neovim"
brew "ripgrep"

# Lua
brew "lua-language-server"
brew "stylua"

# Bash
brew "bash-language-server"
brew "shellcheck"

# oh-my-zsh
brew "zsh-autosuggestions"
brew "powerlevel10k"

# fonts
tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"

# Cask
cask "slack"
cask "vlc"
cask "iterm2"
cask "sourcetree"
cask "spotify"
cask "rectangle"
