#!/usr/bin/env sh

if [ -f ~/.tmux.conf ]; then
  tmux source-file ~/.tmux.conf;
fi

SESSION=metrics-demo
tmux has-session -t $SESSION
if [ $? != 0 ]
then
  PROJECT=$HOME/dev/rails/infinum/metrics-demo

  # src
  tmux new-session -s $SESSION -n src -d
  tmux send-keys -t $SESSION:1 "cd $PROJECT" C-m

  # server
  tmux new-window -n server -t $SESSION
  tmux send-keys -t $SESSION:2 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:2 "bin/rails s" C-m

  # services
  tmux new-window -n services -t $SESSION
  tmux send-keys -t $SESSION:3 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:3 "bundle exec prometheus_exporter" C-m

  tmux select-window -t $SESSION:1
fi

tmux attach -t $SESSION
