#!/usr/bin/env sh

if [ -f ~/.tmux.conf ]; then
  tmux source-file ~/.tmux.conf;
fi

SESSION=rails-startup-threads
tmux has-session -t $SESSION
if [ $? != 0 ]
then
  PROJECT=$HOME/dev/rails/infinum/startup-threads

  # src
  tmux new-session -s $SESSION -n src -d
  tmux send-keys -t $SESSION:1 "cd $PROJECT" C-m

  # client 
  tmux new-window -n client -t $SESSION
  tmux send-keys -t $SESSION:2 "cd $PROJECT/app/assets/javascripts/threads" C-m

  # server
  tmux new-window -n server -t $SESSION
  tmux split-window -v -t $SESSION:3
  tmux send-keys -t $SESSION:3.1 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:3.1 "foreman start" C-m
  tmux send-keys -t $SESSION:3.2 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:3.2 "foreman run rails c" C-m

  # log
  tmux new-window -n log -t $SESSION
  tmux send-keys -t $SESSION:4 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:4 "less -r +F log/development.log" C-m

   tmux select-window -t $SESSION:1
fi

tmux attach -t $SESSION
