#!/usr/bin/env sh

if [ -f ~/.tmux.conf ]; then
  tmux source-file ~/.tmux.conf;
fi

SESSION=rails-hpb-contract
tmux has-session -t $SESSION
if [ $? != 0 ]
then
  BACKEND=$HOME/dev/rails/infinum/hpb-contract
  FRONTEND=$HOME/dev/js/infinum/hpb-contract

  # beckend
  tmux new-session -s $SESSION -n backend -d
  tmux send-keys -t $SESSION:1 "cd $BACKEND" C-m

  # server
  tmux new-window -n server -t $SESSION
  tmux split-window -v -t $SESSION:2
  tmux send-keys -t $SESSION:2.1 "cd $BACKEND" C-m
  tmux send-keys -t $SESSION:2.1 "be foreman start" C-m
  tmux send-keys -t $SESSION:2.2 "cd $BACKEND" C-m
  tmux send-keys -t $SESSION:2.2 "rails c" C-m

  # gulp
  tmux new-window -n webpack -t $SESSION
  tmux split-window -v -t $SESSION:3
  tmux send-keys -t $SESSION:3.1 "cd $FRONTEND" C-m 
  tmux send-keys -t $SESSION:3.1 "n 10.0.0" C-m
  tmux send-keys -t $SESSION:3.1 "npm start" C-m
  tmux send-keys -t $SESSION:3.2 "cd $FRONTEND" C-m

  # frontend
  tmux new-window -n frontend -t $SESSION
  tmux send-keys -t $SESSION:4 "cd $FRONTEND/src/app/ng-app" C-m

  tmux select-window -t $SESSION:1
fi

tmux attach -t $SESSION
