#!/usr/bin/env sh

if [ -f ~/.tmux.conf ]; then
  tmux source-file ~/.tmux.conf;
fi

SESSION=ruby-usfm-transformer
tmux has-session -t $SESSION
if [ $? != 0 ]
then
  PROJECT=$HOME/dev/ruby/infinum/usfm_transformer

  # src
  tmux new-session -s $SESSION -n src -d
  tmux send-keys -t $SESSION:1 "cd $PROJECT" C-m

  # test
  tmux new-window -t $SESSION -n test
  tmux send-keys -t $SESSION:2 "cd $PROJECT" C-m

  tmux select-window -t $SESSION:1
fi

tmux attach -t $SESSION
