#!/usr/bin/env sh

if [ -f ~/.tmux.conf ]; then
  tmux source-file ~/.tmux.conf;
fi

SESSION=rails-bible
tmux has-session -t $SESSION
if [ $? != 0 ]
then
  PROJECT=$HOME/dev/rails/infinum/bible
  USFM_TRANSFORMER=$HOME/dev/ruby/infinum/usfm_transformer

  # src
  tmux new-session -s $SESSION -n src -d
  tmux send-keys -t $SESSION:1 "cd $PROJECT" C-m

  # client
  tmux new-window -n client -t $SESSION
  tmux send-keys -t $SESSION:2 "cd $PROJECT/app/assets/javascripts/app" C-m

  # server
  tmux new-window -n server -t $SESSION
  tmux split-window -v -t $SESSION:3
  tmux send-keys -t $SESSION:3.1 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:3.1 "rails s -p 7010" C-m
  tmux send-keys -t $SESSION:3.2 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:3.2 "rails c" C-m

  # usfm-transformer
  tmux new-window -n usfm-transformer -t $SESSION
  tmux send-keys -t $SESSION:4 "cd $USFM_TRANSFORMER" C-m

  tmux select-window -t $SESSION:1
fi

tmux attach -t $SESSION
