#!/usr/bin/env sh

if [ -f ~/.tmux.conf ]; then
  tmux source-file ~/.tmux.conf;
fi

SESSION=rails-bundler
tmux has-session -t $SESSION
if [ $? != 0 ]
then
  PROJECT=$HOME/dev/rails/infinum/bundler

  # src
  tmux new-session -s $SESSION -n src -d
  tmux send-keys -t $SESSION:1 "cd $PROJECT" C-m

  # admin client
  tmux new-window -n client -t $SESSION
  tmux send-keys -t $SESSION:2 "cd $PROJECT/app/assets/javascripts/admin" C-m

  # server
  tmux new-window -n server -t $SESSION
  tmux split-window -v -t $SESSION:3
  tmux send-keys -t $SESSION:3.1 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:3.1 "less -r +F log/development.log" C-m
  tmux send-keys -t $SESSION:3.2 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:3.2 "rails c" C-m

  # services
  tmux new-window -n services -t $SESSION
  tmux split-window -v -t $SESSION:4
  tmux send-keys -t $SESSION:4.1 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:4.1 "bundle exec sidekiq" C-m
  tmux send-keys -t $SESSION:4.2 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:4.2 "npm start" C-m

  tmux select-window -t $SESSION:1
fi

tmux attach -t $SESSION
