#!/usr/bin/env sh

if [ -f ~/.tmux.conf ]; then
  tmux source-file ~/.tmux.conf;
fi

SESSION=hideme
tmux has-session -t $SESSION
if [ $? != 0 ]
then
  PROJECT=$HOME/dev/rails/infinum/hideme

  # src
  tmux new-session -s $SESSION -n src -d
  tmux send-keys -t $SESSION:1 "cd $PROJECT" C-m

  # server
  tmux new-window -n server -t $SESSION
  tmux split-window -v -t $SESSION:2
  tmux send-keys -t $SESSION:2.1 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:2.1 "less -r +F log/development.log" C-m
  tmux send-keys -t $SESSION:2.2 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:2.2 "rails c" C-m

  # services
  tmux new-window -n services -t $SESSION
  tmux split-window -v -t $SESSION:3
  tmux split-window -h -t $SESSION:3.1
  tmux send-keys -t $SESSION:3.1 "cd $PROJECT" C-m
  # tmux send-keys -t $SESSION:3.1 "ngrok http wholesale.hideme.dev:80" C-m

  tmux send-keys -t $SESSION:3.2 "cd $PROJECT/mock-server" C-m
  tmux send-keys -t $SESSION:3.2 "npm start" C-m

  tmux send-keys -t $SESSION:3.3 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:3.3 "bundle exec sidekiq" C-m

  tmux select-window -t $SESSION:1
fi

tmux attach -t $SESSION
