#!/usr/bin/env sh

if [ -f ~/.tmux.conf ]; then
  tmux source-file ~/.tmux.conf;
fi

SESSION=hailey
tmux has-session -t $SESSION
if [ $? != 0 ]
then
  PROJECT=$HOME/dev/elixir/infinum/concept/hailey-demo

  # src
  tmux new-session -s $SESSION -n src -d
  tmux send-keys -t $SESSION:1 "cd $PROJECT" C-m

  # server
  tmux new-window -n client -t $SESSION
  tmux split-window -v -t $SESSION:2
  tmux send-keys -t $SESSION:2.1 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:2.1 "mix phoenix.server" C-m
  tmux send-keys -t $SESSION:2.2 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:2.2 "iex -S mix" C-m

  tmux select-window -t $SESSION:1
fi

tmux attach -t $SESSION
