#!/usr/bin/env sh

if [ -f ~/.tmux.conf ]; then
  tmux source-file ~/.tmux.conf;
fi

SESSION=rails-codeing-inventory
tmux has-session -t $SESSION
if [ $? != 0 ]
then
  PROJECT=$HOME/dev/rails/codeing/small-company-warehouse/inventory

  # src
  tmux new-session -s $SESSION -n src -d
  tmux send-keys -t $SESSION:1 "cd $PROJECT" C-m

  # server
  tmux new-window -n server -t $SESSION
  tmux split-window -v -t $SESSION:2
  tmux send-keys -t $SESSION:2.1 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:2.1 "bin/rails s -p 7030" C-m
  tmux send-keys -t $SESSION:2.2 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:2.2 "bin/rails c" C-m

  # services
  tmux new-window -n services -t $SESSION
  tmux send-keys -t $SESSION:3.1 "cd $PROJECT" C-m
  tmux send-keys -t $SESSION:3.1 "be sidekiq" C-m

  tmux select-window -t $SESSION:1
fi

tmux attach -t $SESSION
