#!/usr/bin/env sh

if [ -f ~/.tmux.conf ]; then
  tmux source-file ~/.tmux.conf;
fi

SESSION=talks-module-object
tmux has-session -t $SESSION
if [ $? != 0 ]
then
  PROJECT=$HOME/dev/ruby/infinum/talks/module-object

  # main
  tmux new-session -s $SESSION -n src -d
  tmux send-keys -t $SESSION:1 "cd $PROJECT" C-m
fi

tmux attach -t $SESSION
